/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author aconggancuk
 */
public class FGerbong extends javax.swing.JPanel {

    /**
     * Creates new form FGerbong
     */
    public FGerbong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        BtnBack = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        TxtJumlah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CmbJenis = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        TxtKodeIn = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        BtnRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taGerbong = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        taKodeGerbong = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        TxtKode = new javax.swing.JTextField();
        BtnTampil = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();

        TabPane.setToolTipText("");

        BtnBack.setText("BACK");

        BtnSave.setText("SAVE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("JUMLAH");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("JENIS");

        CmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EKSEKUTIF", "BISNIS", "EKONOMI" }));
        CmbJenis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("KODE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(BtnBack))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtKodeIn)
                    .addComponent(CmbJenis, javax.swing.GroupLayout.Alignment.TRAILING, 0, 91, Short.MAX_VALUE)
                    .addComponent(BtnSave, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtJumlah))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TxtKodeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSave)
                    .addComponent(BtnBack))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        TabPane.addTab("INPUT DATA GERBONG", jPanel2);

        BtnRefresh.setText("REFRESH");

        taGerbong.setColumns(20);
        taGerbong.setRows(5);
        jScrollPane2.setViewportView(taGerbong);

        taKodeGerbong.setColumns(20);
        taKodeGerbong.setRows(5);
        jScrollPane4.setViewportView(taKodeGerbong);

        jLabel5.setText("KODE");

        BtnTampil.setText("TAMPIL");

        BtnDelete.setText("DELETE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TxtKode))
                    .addComponent(jScrollPane4))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDelete)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(BtnTampil)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnRefresh))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnRefresh)
                    .addComponent(jLabel5)
                    .addComponent(TxtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTampil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDelete)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        TabPane.addTab("DATA GERBONG", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(TabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnTampil;
    private javax.swing.JComboBox<String> CmbJenis;
    private javax.swing.JTabbedPane TabPane;
    private javax.swing.JTextField TxtJumlah;
    private javax.swing.JTextField TxtKode;
    private javax.swing.JTextField TxtKodeIn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea taGerbong;
    private javax.swing.JTextArea taKodeGerbong;
    // End of variables declaration//GEN-END:variables

    //Method dan Function Input Data
    public String getKodeGerbongIn() {
        return TxtKodeIn.getText();
    }
    
    public String getJenisGerbong() {
        return (String) CmbJenis.getSelectedItem();
    }
    
    public String getJumlahGerbong() {
        return TxtJumlah.getText();
    }
    
    public Object getBtnSave() {
        return BtnSave;
    }
    
    public Object getBtnBack() {
        return BtnBack;
    }
    
    public void reset() {
        TxtKodeIn.setText("");
        CmbJenis.setSelectedIndex(0);
        TxtJumlah.setText("");
    }
    
    //Method dan Function Data Gerbong
    public JTextField getTxtKode() {
        return TxtKode;
    }

    public Object getBtnTampil() {
        return BtnTampil;
    }
    
    public Object getBtnDelete() {
        return BtnDelete;
    }
    
    public Object getBtnRefresh() {
        return BtnRefresh;
    }
    
    public void setDetailGerbong(String s) {
        taGerbong.setText(s);
    }

    public JTextArea getTaGerbong() {
        return taGerbong;
    }
    
    public void setKodeGerbong(String s) {
        taKodeGerbong.setText(s);
    }
    
    public JTextArea getTaKodeGerbong() {
        return taKodeGerbong;
    }
    
   public void resetData() {
        TxtKode.setText("");
        taGerbong.setText("");
    }
    
    public void addListener(ActionListener e) {
        BtnSave.addActionListener(e);
        BtnBack.addActionListener(e);
        BtnDelete.addActionListener(e);
        BtnRefresh.addActionListener(e);
        BtnTampil.addActionListener(e);
   }
}
