/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;


/**
 *
 * @author aconggancuk
 */
public class FKereta extends javax.swing.JPanel {

    /**
     * Creates new form FKereta
     */
    public FKereta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane TabPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtJurusan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CmbJenis = new javax.swing.JComboBox<>();
        BtnSave = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNamaKereta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taKereta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        TxtDataNama = new javax.swing.JTextField();
        BtnTampil = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnRefresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taInfoGerbong = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        taInfoKereta = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtKdGerbong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNmKereta = new javax.swing.JTextField();
        BtnAddGerbong = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        taGerbongToKereta = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        BtnRefreshAll = new javax.swing.JButton();

        jLabel2.setText("NAMA");

        jLabel3.setText("JURUSAN");

        jLabel4.setText("JENIS");

        CmbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eksekutif", "Bisnis", "Ekonomi" }));

        BtnSave.setText("SAVE");

        BtnBack.setText("BACK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSave))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(17, 17, 17))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtNama)
                                    .addComponent(CmbJenis, 0, 99, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(TxtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSave)
                    .addComponent(BtnBack))
                .addContainerGap(233, Short.MAX_VALUE))
        );

        TabPane.addTab("INSERT DATA KERETA", jPanel2);

        taNamaKereta.setColumns(20);
        taNamaKereta.setRows(5);
        jScrollPane1.setViewportView(taNamaKereta);

        taKereta.setColumns(20);
        taKereta.setRows(5);
        jScrollPane2.setViewportView(taKereta);

        jLabel1.setText("NAMA");

        BtnTampil.setText("TAMPIL");

        BtnDelete.setText("DELETE");

        BtnRefresh.setText("REFRESH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtDataNama, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BtnTampil, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnDelete, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(185, 185, 185)
                                .addComponent(BtnRefresh))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(139, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDataNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTampil)
                    .addComponent(BtnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDelete)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        TabPane.addTab("DATA KERETA", jPanel1);

        taInfoGerbong.setColumns(20);
        taInfoGerbong.setRows(5);
        jScrollPane4.setViewportView(taInfoGerbong);

        taInfoKereta.setColumns(20);
        taInfoKereta.setRows(5);
        jScrollPane5.setViewportView(taInfoKereta);

        jLabel8.setText("INFO GERBONG");

        jLabel9.setText("INFO KERETA");

        jLabel10.setText("KODE GERBONG");

        jLabel11.setText("NAMA KERETA");

        BtnAddGerbong.setText("ADD GERBONG TO KERETA");

        taGerbongToKereta.setColumns(20);
        taGerbongToKereta.setRows(5);
        jScrollPane6.setViewportView(taGerbongToKereta);

        jLabel12.setText("INFO ADD GERBONG TO KERETA");

        BtnRefreshAll.setText("REFRESH");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtKdGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(96, 96, 96)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNmKereta, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane5))
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnAddGerbong)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRefreshAll)
                .addGap(318, 318, 318))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtKdGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtNmKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAddGerbong))
                .addGap(18, 18, 18)
                .addComponent(BtnRefreshAll)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        TabPane.addTab("INSERT GERBONG TO KERETA", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddGerbong;
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnRefreshAll;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnTampil;
    private javax.swing.JComboBox<String> CmbJenis;
    private javax.swing.JTextField TxtDataNama;
    private javax.swing.JTextField TxtJurusan;
    private javax.swing.JTextField TxtNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea taGerbongToKereta;
    private javax.swing.JTextArea taInfoGerbong;
    private javax.swing.JTextArea taInfoKereta;
    private javax.swing.JTextArea taKereta;
    private javax.swing.JTextArea taNamaKereta;
    private javax.swing.JTextField txtKdGerbong;
    private javax.swing.JTextField txtNmKereta;
    // End of variables declaration//GEN-END:variables

    //Method dan Function Input 
    public String getTxtNama() {
        return TxtNama.getText();
    }
    
    public String getTxtJurusan() {
        return TxtJurusan.getText();
    }
    
    public String getCmbJenis() {
        return (String) CmbJenis.getSelectedItem();
    }
    
    public Object getBtnSave() {
        return BtnSave;
    }
    
    public Object getBtnBack() {
        return BtnBack;
    }
    
    public void reset() {
        TxtNama.setText("");
        TxtJurusan.setText("");
    }
    
    //Method dan Function Data Kereta
    public String getTxtDataNama(){
        return TxtDataNama.getText();
    }
    public Object getBtnDel() {
        return BtnDelete;
    }
    
    public Object getBtnRefresh() {
        return BtnRefresh;
    }
    
    public Object getBtnDelete() {
        return BtnDelete;
    }
    
    public void setDetailKereta(String s) {
        taKereta.setText(s);
    }
    
    public void setNamaKereta(String s) {
        taNamaKereta.setText(s);
    }
    
    public void resetData() {
        TxtDataNama.setText("");
        taNamaKereta.setText("");
    }

    public JTextArea getTaNamaKereta() {
        return taNamaKereta;
    }

    public JTextArea getTaKereta() {
        return taKereta;
    }

    public Object getBtnTampil() {
        return BtnTampil;
    }
    
    //Method and Function Add Gerbong to Kereta
    public void setInfoGerbong(String s) {
        taInfoGerbong.setText(s);
    }

    public JTextArea getTaInfoGerbong() {
        return taInfoGerbong;
    }
    
    public void setInfoKereta(String s) {
        taInfoKereta.setText(s);
    }

    public JTextArea getTaInfoKereta() {
        return taInfoKereta;
    }
    
    public void setGerbongToKereta(String s) {
        taGerbongToKereta.setText(s);
    }

    public JTextArea getTaGerbongToKereta() {
        return taGerbongToKereta;
    }
    
    public String getTxtKodeGerbong() {
        return txtKdGerbong.getText();
    }
    
    public String getTxtNamaKereta() {
        return txtNmKereta.getText();
    }
    
    public Object getBtnAddGerbong() {
        return BtnAddGerbong;
    }
    
    public Object getBtnRefreshAll() {
        return BtnRefreshAll;
    }
    
    public void resetAll() {
        txtKdGerbong.setText("");
        txtNmKereta.setText("");
        taInfoGerbong.setText("");
        taInfoKereta.setText("");
        taGerbongToKereta.setText("");
    }
    
    public void addListener(ActionListener e) {
        BtnSave.addActionListener(e);
        BtnDelete.addActionListener(e);
        BtnRefresh.addActionListener(e);
        BtnTampil.addActionListener(e);
        BtnBack.addActionListener(e);
        BtnAddGerbong.addActionListener(e);
        BtnRefreshAll.addActionListener(e);
    }
}
