/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author aconggancuk
 */
public class mainMenu extends javax.swing.JPanel {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnTiket = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnRute = new javax.swing.JButton();
        BtnStasiun = new javax.swing.JButton();
        BtnKereta = new javax.swing.JButton();
        BtnGerbong = new javax.swing.JButton();

        BtnTiket.setText("TIKET");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI DATA PENJUALAN TIKET");

        BtnRute.setText("RUTE");

        BtnStasiun.setText("STASIUN");

        BtnKereta.setText("KERETA");

        BtnGerbong.setText("GERBONG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGerbong)
                        .addGap(18, 18, 18)
                        .addComponent(BtnKereta)
                        .addGap(18, 18, 18)
                        .addComponent(BtnStasiun)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRute)))
                .addGap(18, 18, 18)
                .addComponent(BtnTiket)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGerbong)
                    .addComponent(BtnKereta)
                    .addComponent(BtnStasiun)
                    .addComponent(BtnRute)
                    .addComponent(BtnTiket))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGerbong;
    private javax.swing.JButton BtnKereta;
    private javax.swing.JButton BtnRute;
    private javax.swing.JButton BtnStasiun;
    private javax.swing.JButton BtnTiket;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void addListener(ActionListener e){
        BtnGerbong.addActionListener(e);
        BtnKereta.addActionListener(e);
        BtnRute.addActionListener(e);
        BtnStasiun.addActionListener(e);
        BtnTiket.addActionListener(e);        
    }

    public Object getBtnGerbong() {
        return BtnGerbong;
    }
    
    public Object getBtnKereta(){
        return BtnKereta;
    }
    
    public Object getBtnRute() {
        return BtnRute;
    }
    
    public Object getBtnStasiun(){
        return BtnStasiun;
    }
    
    public Object getBtnTiket(){
        return BtnTiket;
    }
    
}
